config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
  root 'user/homes#top'
  get 'admin'=>'admin/homes#top'
  
  devise_for :user,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  #ユーザー用
  namespace :user, :path => '' do
    get '/about'=>'homes#about'
    
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'users/:id/quit'=>'users#quit', as: 'users/quit'
    patch 'users/remove'
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    resources :makers, only: [:show]
    resources :genres, only: [:show]
    resources :cc_classes, only: [:show]
    
    resources :orders, only: [:new, :create, :index, :show]
    get 'orders/:id/comp'=>'orders#comp'
    post 'orders/info'=>'orders#info'
    
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :item_comments, only: [:create, :destroy]
    end
    
    get 'search'=>'searches#search_result'
  end
  
  #管理者用
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:index, :show]
    
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :makers, only: [:index, :create, :edit, :update, :destroy]
    resources :cc_classes, only: [:index, :create, :edit, :update, :destroy]
    
    resources :items, only: [:index, :show, :edit, :update, :destroy]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_one_attached :profile_image
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(last_name: content)
    else
      User.where('last_name LIKE ?', '%' + content + '%')
    end
  end
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders=Order.all
    @orders=Order.all.page(params[:page]).per(10)
  end

  def show
    @order=Order.find(params[:id])
    @order_item = @order.order_items
  end
  
  private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users=User.page(params[:page]).per(10)
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :is_deleted)
  end
end

app/controllers/user/addresses_controller.rb
class User::AddressesController < ApplicationController
  def index
    @address = Address.new
    @addresses = Address.all
  end
  
  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    @address.save
  end

  def edit
    @address = Address.find(params[:id])
    if @address.user_id == current_user.id
      render "edit"
    else
      redirect_to address_path
    end
  end
  
  def update
    @address=Address.find(params[:id])
    @address.update(address_params)
    redirect_to user_addresses_path
  end
  
  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to address_path
  end
  
  private
  
  def address_params
    params.require(:address).permit(:user_id, :postal_code, :address, :name)
  end
end

app/controllers/user/cc_classes_controller.rb
class User::CcClassesController < ApplicationController
  def show
    @cc_classes=CcClass.all
    @cc_class=CcClass.find(params[:id])
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
    def create
        item=Item.find(params[:item_id])
        @favorite=current_user.favorites.new(item_id: item.id)
        @favorite.save
        redirect_to request.referer
    end
    
    def destroy
        item=Item.find(params[:item_id])
        @favorite=current_user.favorites.find_by(item_id: item.id)
        @favorite.destroy
        redirect_to request.referer
    end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  def show
    @genres=Genre.all
    @genre=Genre.find(params[:id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @item=Item.limit(4).order("created_at DESC")
    @genres=Genre.all
    @makers=Maker.all
    @cc_classes=CcClass.all
  end

  def about
  end
end

app/controllers/user/item_comments_controller.rb
class User::ItemCommentsController < ApplicationController
    def create
        @item=Item.find(params[:item_id])
        item_comment=current_user.item_comments.new(item_comment_params)
        item_comment.item_id=@item.id
        item_comment.save
        redirect_to user_item_path(@item)
    end
    
    def destroy
        ItemComment.find(params[:id]).destroy
        @item=Item.find(params[:item_id])
        redirect_to user_item_path(@item)
    end
    
    private
    
    def item_comment_params
        params.require(:item_comment).permit(:item_comment)
    end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
  #before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  def new
    @item=Item.new
  end
  
  def create
    @item=Item.new(item_params)
    @item.user_id=current_user.id
    if @item.save
    redirect_to user_item_path(@item)
    else
    @items=Item.all
    render 'index'
    end
  end

  def index
    @items=Item.all
    @genres=Genre.all
    @items=Item.all.page(params[:page]).per(20)
  end

  def show
    @item=Item.find(params[:id])
    @item_comment=ItemComment.new
  end

  def edit
    @item=Item.find(params[:id])
    if @item.user_id=current_user.id
      render :edit
    else
      redirect_to user_items_path
    end
  end
  
  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    redirect_to user_item_path(@item)
  end
  
  def destroy
    @item=Item.find(params[:id])
    @item.destroy
    redirect_to user_items_path
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id, :maker_id, :cc_class_id, :user_id, :name, :description, :price, :sale_method, :sale_status, :image, :cc, :year, :km, :color, :country)
  end
end

app/controllers/user/makers_controller.rb
class User::MakersController < ApplicationController
  def show
    @makers=Maker.all
    @maker=Maker.find(params[:id])
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
  def new
    @order = Order.new
  end
  
  def info
    #情報確認画面
    @items = current_user.items
    @order = Order.new(order_params)
    #@order.billing_amount = ordered_price + shipping
    if params[:order][:select_address] == "0"
      @order = Order.new(order_params)
      @order.postal_code = current_user.postal_code
      @order.address = current_user.address
      @order.name = current_user.first_name + current_user.last_name
    elsif params[:order][:select_address] == "1"
      @order = Order.new(order_params)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    elsif params[:order][:select_address] == "2"
      @order.postal_code = ordered.postal_code
      @order.address = ordered.address
      @order.name = ordered.name
    else
      flash[:notice] = "errer"
      render :new
    end
  end
  
  
  def create
    #確定処理
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save!
    current_customer.cart_items.each do |cart_item|
      @order_item = OrderItem.new
      @order_item.item_id = cart_item.item_id
      @order_item.item_count = cart_item.item_count
      @order_item.ordered_price = (cart_item.item.price*1.1).round.to_i
      @order_item.order_id = @order.id
      @order_item.save
    end
    current_customer.cart_items.destroy_all
    redirect_to public_orders_complete_path
  end

  def comp
  end

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_item = @order.order_items
  end
  
  private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name)
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController

  def search_result
	@model = params[:model]
	@content = params[:content]
	@method = params[:method]
	if @model == 'item'
	  @records = Item.search_for(@content, @method)
	elsif @model == 'user'
	  @records = User.search_for(@content, @method)
	end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  # 退会しているかを判断するメソッド
  def user_state
    ## 【処理内容1】 入力されたemailからアカウントを1件取得
    @user = User.find_by(email: params[:user][:email])
    ## アカウントを取得できなかった場合、このメソッドを終了する
    return if !@user
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
    ## 【処理内容3】
    redirect_to new_user_registration_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/user/orders/comp.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-9'>
            <h1>ご注文ありがとうございました！</h1>
        </div>
    </div>
</div>

app/views/user/orders/index.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-lg-12'>
            <table class='table table-bordered'>
            <thead>
                <tr>
                    <th>注文日</th>
                    <th>配送先</th>
                    <th>注文商品</th>
                    <th>支払金額</th>
                    <th>ステータス</th>
                    <th>注文詳細</th>
                </tr>
            </thead>
            <% @orders.each do |order| %>
            <tbody>
                <tr>
                    <td><%= order.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
                    <td><%= order.ordered_postal_code %><%= order.ordered_address %><%= order.receriver_name %></td>
                    
                    <td><% order.order_items.each do |order_item| %><%= order_item.item.name %><% end %></td>
                    
                    
                    <td><% order.order_items.each do |order_item| %><%= order_item.item.price %><% end %></td>
                    
                    <td><%= order.order_status %></td>
                    <td><%= link_to '表示する', public_order_path(order.id), class: 'btn btn-success'  %></td>
                </tr>
            </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>

app/views/user/orders/info.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-9'>
            <div>
            <p>商品名</p>
            <p>単価(税込)</p>
            <p>数量</p>
            <p>小計</p>
            <% @items.each do |item| %>
                <%= image_tag item.image, size: "50x50", fallback: 'no_image_jpg' %><%= item.name %>
                <%= (item.price*1.1).round.to_i %>
                
            <% end %> 
            <p>送料</p>
            <p>800</p>
            <p>商品合計</p>
            <%= @total_price %>
                <p>請求金額</p>
            <%= @order.billing_amount %>
            <p>支払方法</p>
            <%= @order.payment_method %>
            <p>お届け先</p>
                <%= @order.postal_code %>
                <%= @order.address %>
                <%= @order.name %>
            </div>
            <div>
                <!-- 情報 -->
            <%= form_with model: @order, url: user_orders_path do |f| %>
            <%= f.hidden_field :postal_code, value: @order.postal_code %>
            <%= f.hidden_field :address, value: @order.address %>
            <%= f.hidden_field :name, value: @order.name %>
            <%= f.hidden_field :payment_method, value: @order.payment_method %>

                <%= f.submit "注文を確定する" %>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/user/orders/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-9'>
            <%= notice %>
            <h2>注文情報入力</h2>
                <h3>支払方法</h3>
                    <%= form_with model: @order,url: user_orders_info_path do |f| %>
                        <%= f.radio_button :payment_method, :card %>
                            <%= f.label :payment_method, "クレジットカード",{value: :card, style: "display: inline-block;"} %>
                        <%= f.radio_button :payment_method, :bank %>
                            <%= f.label :payment_method, "銀行振込",{value: :bank, style: "display: inline-block;"} %>
                           
                <h3>お届け先</h3>
                <div class='row'>
                    <div class='col-xs-9'>
                            <%= f.radio_button :select_address, 0 %>
                                
                                    <h4>ご自身の住所</h4>
                                        <%= "#{current_user.postal_code}""#{current_user.address}" %>
                                    <%= "#{current_user.last_name}""#{current_user.first_name}" %>
                                
                            <%= f.radio_button :select_address, 1 %>
                                
                                </div>
                                </div>
                                <div class='row'>
                                    <div class='col-xs-9'>
                                    <h4>登録済住所</h4>
                                        <%= f.select :address_id, options_from_collection_for_select(Address.all, :id, :address_display) %>
                                
                            <%= f.radio_button :select_address, 2 %>
                                
                                </div>
                                </div>
                                <div class='row'>
                                    <div class='col-xs-9'>
                            <h4>新しいお届け先</h4>
                                <%= f.label :"郵便番号（ハイフンなし）" %>
                                <%= f.text_field :postal_code %>
                                <%= f.label :"住所" %>
                                <%= f.text_field :address %>
                                <%= f.label :"宛名" %>
                                <%= f.text_field :name %>
                                </div>
                                </div>
                    <%= f.submit "確認画面へ進む" %>
               
            <% end %>
        </div>
    </div>
</div>

app/views/user/orders/show.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-9'>
            <div>
            <h4>注文情報</h4>
                <p>注文日</p>
                    <%= @order.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
                <p>配送先</p>
                    <%= @order.ordered_postal_code %>
                    <%= @order.ordered_address %>
                    <%= @order.receriver_name %>
                <p>支払方法</p>
                <p>ステータス</p>
                    <%= @order.order_status %>
            <h4>請求情報</h4>
                <p>商品合計</p>
                    <%= @total_price %>
                <p>配送料</p>
                <p>800</p>
                <p>ご請求額</p>
                    <%= @order.billing_amount %>
            </div>
            <div>
            <h4>注文内容</h4>
                <% @order_item.each do |order_item| %>
                    <p>商品<%= order_item.item.name %></p>
                    <p>単価（税込）<%= order_item.ordered_price %>円</p>
                    <p>個数<%= order_item.item_count %></p>
                    <p>小計<%= (order_item.ordered_price*order_item.item_count) %>円</p>
                <% end %>
            </div>
        </div>
    </div>
</div>