config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
  root 'user/homes#top'
  get 'admin'=>'admin/homes#top'
  
  devise_for :user,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  #ユーザー用
  namespace :user, :path => '' do
    get '/about'=>'homes#about'
    
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'users/:id/quit'=>'users#quit', as: 'users/quit'
    patch 'users/remove'
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    resources :makers, only: [:show]
    resources :genres, only: [:show]
    resources :cc_classes, only: [:show]
    
    resources :orders, only: [:new, :create, :index, :show]
    get 'orders/:id/comp'=>'orders#comp'
    post 'orders/info'=>'orders#info'
    
    resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :item_comments, only: [:create, :destroy]
    end
    
    get 'search'=>'searches#search_result'
  end
  
  #管理者用
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:index, :show]
    
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :makers, only: [:index, :create, :edit, :update, :destroy]
    resources :cc_classes, only: [:index, :create, :edit, :update, :destroy]
    
    resources :items, only: [:index, :show, :edit, :update, :destroy]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
    
    validates :postal_code, :name, :address, presence: true
    
    def address_all
      self.postal_code+' '+self.address+' '+self.name
    end
    
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cc_class.rb
class CcClass < ApplicationRecord
    has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :user
  belongs_to :genre
  belongs_to :maker
  belongs_to :cc_class
  has_many :favorites, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  enum sale_status: { 販売停止中: 0, 販売中: 1 }
  enum sale_method: { 引き渡しのみ: 0, 配送のみ: 1, 配送と引き渡し: 2 }
  
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  
  def self.search_for(content, method)
    if method == 'perfect'
      Item.where(name: content)
    else
      Item.where('name LIKE ?', '%'+content+'%')
    end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/maker.rb
class Maker < ApplicationRecord
    has_many :items
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_one_attached :profile_image
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(last_name: content)
    else
      User.where('last_name LIKE ?', '%' + content + '%')
    end
  end
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @item=Item.limit(4).order("created_at DESC")
    @genres=Genre.all
    @makers=Maker.all
    @cc_classes=CcClass.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :conigure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        case resource
        when Admin
            admin_path
        when User
            root_path
        end
    end
    
    protected
    
    def conigure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
    end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @item=Item.limit(4).order("created_at DESC")
    @genres=Genre.all
    @makers=Maker.all
    @cc_classes=CcClass.all
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/items_helper.rb
module User::ItemsHelper
end

app/helpers/user/makers_helper.rb
module User::MakersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/homes/top.html.erb
<div class='container'>
    <div class='text-center'>
        <h1 class='font-weight-bolder'>バイクを探す</h1>
    </div>
    <div class='mt-4'><h3 class='font-weight-bolder'><i class="fa-solid fa-motorcycle"></i> 新着バイク　<%= link_to '一覧を見る', user_items_path %></h3></div>
    <div class='row'>
        <div class='d-flex flex-wrap'>
            <% @item.each do |item| %>
            <div class="card mx-2 shadow-lg">
            <div class='card-body'>
            <%= link_to user_item_path(item) do %>
            <% if item.image.attached? %>
            <%= image_tag item.image, size: "200x200" %>
            <% else %>
            <%= image_tag 'assets/images/ネイキッド.png', size: "200x200" %>
            <% end %>
            <% end %>
            <div class='card-text'><%= item.maker.name %></div>
            <div class='card-text'><%= item.name %></div>
            <div class='card-text'>本体価格：<font size='6' color='#ff0000'><%= (item.price*1.1*0.0001).round.to_i %></font>万円（税込）</div>
            </div>
            </div>
            <% end %>
        </div>
    </div>
    <div class='mt-4'><h3 class='font-weight-bolder'><i class="fa-solid fa-motorcycle"></i> メーカーから探す</h3></div>
    <div class='row'>
        <div class='d-flex flex-wrap'>
            <% @makers.each do |maker| %>
            <div class='col-md-6'>
                <%= link_to user_maker_path(maker),class: 'outline-primary' do %>
                <h4>・<%= maker.name %>：<%= maker.items.count %>台</h4>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
    <div class='mt-4'><h3 class='font-weight-bolder'><i class="fa-solid fa-motorcycle"></i> タイプから探す</h3></div>
    <div class='row'>
        <div class='d-flex flex-wrap'>
            <% @genres.each do |genre| %>
            <div class='col-md-6'>
                <%= link_to user_genre_path(genre),class: 'outline-primary' do %>
                <h4>・<%= genre.name %>：<%= genre.items.count %>台</h4>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
    <div class='mt-4'><h3 class='font-weight-bolder'><i class="fa-solid fa-motorcycle"></i> 排気量から探す</h3></div>
    <div class='row'>
        <div class='d-flex flex-wrap'>
            <% @cc_classes.each do |cc_class| %>
            <div class='col-md-6'>
                <%= link_to user_cc_class_path(cc_class),class: 'outline-primary' do %>
                <h4>・<%= cc_class.name %>：<%= cc_class.items.count %>台</h4>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
</div>